
version: '3.8'

services:
  psql-0:
    container_name: psql-0
    image: docker.io/bitnami/postgresql:14
    volumes:
      - psql_0_data:/bitnami/postgres
      - ~/Documents/chainlink-node/.psql-0/pg_hba.conf:/bitnami/postgresql/conf/pg_hba.conf
    env_file: 
      - ~/Documents/chainlink-node/.psql-0/.env
    networks:
      - service
    healthcheck:
      test: pg_isready -U chainlink
      interval: 10s
      timeout: 5s
      retries: 5
          
  psql-1:
    container_name: psql-1
    image: docker.io/bitnami/postgresql:14
    depends_on:
      - psql-0
    env_file: 
      - ~/Documents/chainlink-node/.psql-1/.env
    networks:
      - service

  chainlink-node:
    container_name: chainlink-node
    image: smartcontract/chainlink:1.6.0-nonroot
    volumes:
      - ~/Documents/chainlink-node/.chainlink-rinkerby:/chainlink
    env_file:
     - ~/Documents/chainlink-node/.chainlink-rinkerby/.env
    ports:
      - "6688:6688"
    command:
      - local
      - node
      - -p 
      - /chainlink/.keystore
      - -a
      - /chainlink/.api
    networks:
      - service
    depends_on:
      psql-0:
        condition: service_healthy      

volumes:
  psql_0_data:
    driver: local

networks:
  service:
    driver: bridge